# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/
# and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
BASH_SHELLCHECK_ARGUMENTS: -e "SC2162"
CLEAR_REPORT_FOLDER: true
DISABLE_ERRORS: false
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JSON_V8R
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - PYTHON_BLACK
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_LS_LINT
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRIVY
  - REPOSITORY_TRUFFLEHOG
  - SPELL_LYCHEE
  - SPELL_PROSELINT
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT
FAIL_IF_UPDATED_SOURCES: false
FILEIO_REPORTER: false
FILTER_REGEX_EXCLUDE: none
FLAVOR_SUGGESTIONS: false
FORMATTERS_DISABLE_ERRORS: false
IGNORE_GITIGNORED_FILES: true
LINTER_RULES_PATH: .linters
LOG_LEVEL: INFO
MARKDOWN_DEFAULT_STYLE: markdownlint
MARKDOWN_MARKDOWN_LINK_CHECK_RULES_PATH: .linters
PARALLEL: true
PRINT_ALPACA: false
PYTHON_BANDIT_RULES_PATH: .linters
PYTHON_BANDIT_CONFIG_FILE: .bandit.yml
PYTHON_FLAKE8_RULES_PATH: .linters
PYTHON_PYLINT_FILTER_REGEX_EXCLUDE: tests/.*
REPOSITORY_LS_LINT_RULES_PATH: .linters
REPOSITORY_SEMGREP_RULESETS:
  [
    "p/comment",
    "p/cwe-top-25",
    "p/docker-compose",
    "p/dockerfile",
    "p/owasp-top-ten",
    "p/python",
    "p/r2c-security-audit",
    "p/secure-defaults",
  ]
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
SPELL_PROSELINT_RULES_PATH: .linters
SPELL_VALE_RULES_PATH: .linters
