gemini: DUMMY_API_KEY_FOR_TESTING_PURPOSES
openai: sk-proj-DUMMY_API_KEY_FOR_TESTING_PURPOSES
anthropic: sk-ant-api03-DUMMY_API_KEY_FOR_TESTING_PURPOSES
groq: DUMMY_API_KEY_FOR_TESTING_PURPOSES
xai: DUMMY_API_KEY_FOR_TESTING_PURPOSES
mistral: DUMMY_API_KEY_FOR_TESTING_PURPOSES
deepseek: DUMMY_API_KEY_FOR_TESTING_PURPOSES
